### ISSUE TITLE
Support for Angular Material 9

### ISSUE THREAD

**Issue by matcho** [merlosy/ngx-material-file-input#45]
Hi.

Trying to compile with Angular Material 9 (exactly `9.0.0-rc.7`), I get errors looking like this :

```
import { CanUpdateErrorStateCtor, ErrorStateMatcher } from '@angular/material';
                                                           ~~~~~~~~~~~~~~~~~~~
../node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts:3:35
error TS2306: File '(...)/node_modules/@angular/material/index.d.ts' is not a module.
```

It seems related to the fact that from version 9, Angular Material does not export all its classes in `index.d.ts` anymore, and one has to import them from deeper paths, for ex:
```
import { ErrorStateMatcher } from "@angular/material/core"
```

It's hopefully not such a big deal to update, maybe you have plans for this ?

Thank you, the file input is great by the way !
Mathias

**Comment by KarlJorgen** [comment]
Hi
Any news about a new release for Angular 9?

**Comment by damogallagher** [comment]
HI

I encountered the same issue, just wondering if there is a workaround available or an update planned for this library?

**Comment by jm06487** [comment]
any updates?

**Comment by merlosy** [comment]
Hi all! I'm a bit busy for now, i will try to make a new release during the weekend :) thanks @matcho for the PR and everyboby for the reviews!

**Comment by jsanz1209** [comment]
Hi @merlosy! Would it be very difficult for you accept the pull request, today? only it would be to change the angular material paths. My project is depending on you for this :)

Thanks very much in advances.

**Comment by rsuk** [comment]
@merlosy Would be really valuable for me too (is the last remaining issue blocking an Angular 9 upgrade), and would build confidence generally in using your library in active projects.

**Comment by d00lar** [comment]
yep me also please appove this ;)

**Comment by w0ns88** [comment]
Same here. When can we expect the PR to go through?

**Comment by WayneBarnard** [comment]
Any update on this?

**Comment by davidkarlsen** [comment]
Folks - keep your hair on and read the tracker - he says he's gonna look at it in the weekend.

**Comment by chroniclesBR** [comment]
Waiting the update too

**Comment by merlosy** [comment]
#47 seems also related to this

**Comment by jm06487** [comment]
should we be expecting a release before the end of the week?

**Comment by merlosy** [comment]
Hi folks! the new version [2.1.0](https://github.com/merlosy/ngx-material-file-input/releases/tag/v2.1.0) compatible with angular 9 is out.

**Comment by rsuk** [comment]
> Hi folks! the new version [2.1.0](https://github.com/merlosy/ngx-material-file-input/releases/tag/v2.1.0) compatible with angular 9 is out.

Many thanks for this - I for one really appreciate it.

**Comment by KarlJorgen** [comment]
> Hi folks! the new version [2.1.0](https://github.com/merlosy/ngx-material-file-input/releases/tag/v2.1.0) compatible with angular 9 is out.

Great work mate.

**Comment by jm06487** [comment]
> > Hi folks! the new version [2.1.0](https://github.com/merlosy/ngx-material-file-input/releases/tag/v2.1.0) compatible with angular 9 is out.
> 
> Many thanks for this - I for one real

> Hi folks! the new version [2.1.0](https://github.com/merlosy/ngx-material-file-input/releases/tag/v2.1.0) compatible with angular 9 is out.

Thank you much for this.   Works great!!!
