### PR TITLE
Fix #45 Support for Angular Material 9

### LINKED ISSUE #45: Support for Angular Material 9
Hi.

Trying to compile with Angular Material 9 (exactly `9.0.0-rc.7`), I get errors looking like this :

```
import { CanUpdateErrorStateCtor, ErrorStateMatcher } from '@angular/material';
                                                           ~~~~~~~~~~~~~~~~~~~
../node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts:3:35
error TS2306: File '(...)/node_modules/@angular/material/index.d.ts' is not a module.
```

It seems related to the fact that from version 9, Angular Material does not export all its classes in `index.d.ts` anymore, and one has to import them from deeper paths, for ex:
```
import { ErrorStateMatcher } from "@angular/material/core"
```

It's hopefully not such a big deal to update, maybe you have plans for this ?

Thank you, the file input is great by the way !
Mathias

### PR DESCRIPTION
**Pull request by matcho**
Fixes #45 - update imports from '@angular/material'

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@merlosy PTAL?

**Comment by bilelkhalsi** [comment]
can we get this merged ?

**Comment by luancurti** [comment]
> update imports from '@angular/material'

@matcho You can mention the #45 on you description to close this issue automatically when this PR is merged

**Comment by merlosy** [comment]
I have limited access to internet atm. I will be able to look into it this weekend tops.

**Comment by saithis** [comment]
@merlosy The lib dependencies didn't get updated... so I don't see any inconsistencies. Just the deprecated and with ng9 removed @angular/material imports got fixed, which makes this lib compatible with ng8 and ng9. If you update the lib to ng9, then it will probably not be compatible with ng8 anymore.

**Comment by davidkarlsen** [comment]
When I run tests I get:
```
Compiling ngx-material-file-input : es2015 as esm2015
[32m16 02 2020 09:29:11.395:INFO [karma-server]: [39mKarma v4.4.1 server started at http://0.0.0.0:9876/
[32m16 02 2020 09:29:11.397:INFO [launcher]: [39mLaunching browsers FirefoxHeadless, ChromeCustom with concurrency 1
[32m16 02 2020 09:29:11.418:INFO [launcher]: [39mStarting browser FirefoxHeadless

ERROR in [96mnode_modules/ngx-material-file-input/lib/file-input/file-input-mixin.d.ts[0m:[93m2[0m:[93m60[0m - [91merror[0m[90m TS2306: [0mFile '/home/jenkins/agent/workspace/c-jfr-js-client_feature_angular9/node_modules/@angular/material/index.d.ts' is not a module.

[7m2[0m import { CanUpdateErrorStateCtor, ErrorStateMatcher } from '@angular/material';
[7m [0m [91m                                                           ~~~~~~~~~~~~~~~~~~~[0m
[96mnode_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts[0m:[93m3[0m:[93m35[0m - [91merror[0m[90m TS2306: [0mFile '/home/jenkins/agent/workspace/c-jfr-js-client_feature_angular9/node_modules/@angular/material/index.d.ts' is not a module.

[7m3[0m import { ErrorStateMatcher } from '@angular/material';
[7m [0m [91m                                  ~~~~~~~~~~~~~~~~~~~[0m
[96mnode_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts[0m:[93m9[0m:[93m22[0m - [91merror[0m[90m TS2720: [0mClass 'FileInputComponent' incorrectly implements class 'MatFormFieldControl<FileInput>'. Did you mean to extend 'MatFormFieldControl<FileInput>' and inherit its members as a subclass?
  Type 'FileInputComponent' is missing the following properties from type 'MatFormFieldControl<FileInput>': stateChanges, errorState

[7m9[0m export declare class FileInputComponent extends FileInputMixinBase implements MatFormFieldControl<FileInput>, ControlValueAccessor, OnInit, OnDestroy, DoCheck {
[7m [0m [91m                     ~~~~~~~~~~~~~~~~~~[0m

error Command failed with exit code 1.
```

**Comment by merlosy** [comment]
@saithis thanks for the clarification. I'm still not sure how I can automate test against version 8 and 9. I'll test it quickly before releasing a 2.1.0 version
